---
title: "서울시 상권의 지역사회 경제 리질리언스 관련 요인과 취약성 예측: 코로나19 장기화·회복기 폐업 및 매출 경로의 비교를 중심으로"
author: "원치현(국민대학교 행정학과)"
date: today
format:
  html:
    embed-resources: true
    toc: true
    toc-depth: 3
    code-fold: true
    theme: paper
execute:
  echo: true
  warning: false
---

# 1. Initial setting

## Loading packages

```{r}
#| label: setup

source("C:\Users\chwou\Desktop\graduate\04_analysis\workspace\ml-paper-2026\projects\chwoun0515\code\initial.R")
```

[Back to top](#top)


# 2. Data preparation

```{r}
#| label: data-prep

source("C:\Users\chwou\Desktop\graduate\04_analysis\workspace\ml-paper-2026\projects\chwoun0515\code\data.R")
```

[Back to top](#top)


## Data exclusion and split

```{r}
#| label: split

```

[Back to top](#top)


# 3. Data review

## Descriptive statistics

```{r}
#| label: descriptive


```

[Back to top](#top)


# 4. Estimation

```{r}
#| label: estimation


```

[Back to top](#top)


# 5. Vizualization

## Figure 1. xxx

```{r}
#| label: fig1

```

## Figure 2. xxx

```{r}
#| label: fig2

```

[Back to top](#top)
